name: Release

on:
  release:
    types: [created]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    environment: release
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: Release ${{ github.event.release.tag_name }}
          draft: false
          prerelease: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Builder
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build .exe
        run: |
          pyinstaller -F src/rates.py
          move dist\rates.exe rates.exe
      - name: Store .exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rates.exe
          asset_name: rates.exe
          asset_content_type: application/zip
      - name: Store .xlsx
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ROZNICE KURSOWE.xlsm
          asset_name: ROZNICE KURSOWE.xlsm
          asset_content_type: application/zip
